### PR TITLE
Homepage is now Nek_users.html (not index.html)

### PR DESCRIPTION
**Pull request by RonRahaman**
These changes will (hopefully) make it easier to update the NekDoc Project Page:
* The 'make html' target will compile the webpage such that Nek_users.html is the table of contents.  Previously, I had hacked it so index.hml was the TOC, which needlessly complicated the repo.  
*  The 'make clean' target removes unnecessary artifacts from htlatex.
*  The .gitignore ignores everything unrelated to the webpage or PDF doc.  

With the changes I've introduced, I propose this workflow to keep the Project Page up-to-date

1. Do all LaTex development on the master branch
2. Merge changes from master into gh-pages
3. On gh-pages branch, recompile html and push changes

Following this workflow we would NEVER update LaTex on gh-pages before updating master; NOR merge any changes from gh-pages into master.  

Let me know what you think!

### CODE REVIEW

**Comment by maxhutch** [comment]
Is there any reason to track any history in `gh-pages`?  For [my pages](http://maxhutch.github.io/nek/), I force push a single-commit branch on top of gh-pages every time.  See [`pub_doc` in `makefile.template`](https://github.com/maxhutch/nek/blob/box/makefile.template#L197)

**Comment by maxhutch** [comment]
Force pushing over `gh-pages` also keeps the repo from accumulating copies of binary files that we want in `gh-pages` for links, but otherwise wouldn't want in a git repo (I'm thinking the pdf output, which @oanaoana wants for links from the website).

**Comment by RonRahaman** [comment]
I think that's a fine idea.

**Comment by maxhutch** [comment]
I could work on this and open a PR tomorrow, or take a look at what you end up with if you want to take a shot.

**Comment by michel2323** [comment]
Two comments: 

* The bibtex generation is disabled on the gh-pages branch.
* .gitignore should maybe not ignore the pdf on the gh-pages branch as the webpage links directly to that file. Any comments on that?

**Comment by RonRahaman** [comment]
Re: bibtex generation, thanks for pointing that out.  I think we'll need to change that on master, too?  

Re: the .gitignore, I believe I added !Nek_user.pdf so that it doesn't ignore the PDF...

**Comment by michel2323** [comment]
bibtex was added to master too.

**Comment by RonRahaman** [comment]
And just to be clear... From the WordPress site, would you rather link to master/Nek_users.pdf or gh-branches/Nek_users.pdf?  I'm in favor of the latter, so master will only have source files.

**Comment by RonRahaman** [comment]
Otherwise, I'm happy to close this PR and make a new one with Max's idea (add a target in master/Makefile to update gh-branches; and don't track the history of gh-branches)

**Comment by maxhutch** [comment]
I agree with @RonRahaman : 
 - We should point to `gh-branches/Nek_users.pdf`
 - `master` should be source only.

**Comment by oanaoana** [comment]
Great whatever you decide! I have full confidence
If someone can hand me a small readme at the end with what I should do I'd be even happier :)

Oana
________________________________________

**Comment by RonRahaman** [comment]
Thanks y'all!  Expect a new PR soon...

**Pull request closed without merging**
