### PR TITLE
Removed the "WHY?"s from the manual

### PR DESCRIPTION
**Pull request by lcarasik**
The "WHY"S in the user manual under 3.4 Data Layout in my opinion shouldn't be included in the manual. I believe the why is due to Fortran being column major and the way the memory can be accessed through the indexing scheme. Can we address the "why" as an issue to ensure we properly address it?

### CODE REVIEW

**Comment by oanaoana** [comment]
We know the 'WHY?' of course, it was there for pedagogical reasons to make the user think (Paul had this style in some older document). If the WHY is removed then we need to make sure that the explanation in the paragraph is extensive enough, i.e. array unrolling, memory access, vectorization etc.

**Comment by RonRahaman** [comment]
Thanks for this!  Could you maintain a reference to the "WHY's" somehow, either as a GitHub Issue or even just a comment in the Tex (probably the former, if it can be easily expressed)?  
I'd just like to make sure they get fixed eventually.

**Comment by lcarasik** [comment]
I can understand why previously they were kept in, but for a more "formal" manual looks better to have it explained out. I'm happy to help by writing an explanation as long as someone is willing to make sure it is correct (which I assume someone is)!

If it came across as "we didn't know", it was more of "I figure people know, it just hasn't been changed/I don't know the specific reason for keeping them in there."

**Comment by oanaoana** [comment]
Thanks! Sure go ahead, I'll look at it of course! Check out the last chapter in Paul's book for inspiration.

**Comment by lcarasik** [comment]
After reading the chapter in Paul's book and rereading the section, it seems the "WHY?"s are already (at least partially) explained in the text [1],[2],[3] and the paragraph above it. Is rewriting the current list/paragraph a better idea then?

**Comment by lcarasik** [comment]
Just wanted to follow up, any thoughts on this?

**Comment by lcarasik** [comment]
Just posting again for a followup + review of the change.

**Comment by stgeke** [comment]
I'll close this for now as this changes is no longer compatible with the latest source. Feel free to open this discussion again (as an issue)

**Pull request closed without merging**
