### PR TITLE
Update ns_eqns to fix Re and Fr numbers

### PR DESCRIPTION
**Pull request by lcarasik**
The Re definition in the manual is incorrect and flipped. Also an erroneous Fr was added to it.

### CODE REVIEW

**Comment by lcarasik** [comment]
@RonRahaman Any possibility of this being looked at or appropriate reviewers being added?

**Comment by lcarasik** [comment]
Thanks Paul!

**Comment by lcarasik** [comment]
These changes haven't been integrated into the currently available manual found here:  http://nek5000.github.io/NekDoc/Nek_users.pdf

**Comment by lcarasik** [comment]
These changes have been fixed or actually added in the most recent update in the Nek5000 documentation.

**Comment by stgeke** [comment]
Please add an issue for this.

**Pull request merged**
